#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
	reload_service
}

reload_service() {
	[ -x /usr/bin/netqueue-apply.sh ] || return 0
	/usr/bin/netqueue-apply.sh apply
}

service_triggers() {
	procd_add_reload_trigger "netqueue"
	procd_add_reload_trigger "network"
	procd_add_raw_trigger "interface.*" 2000 /usr/bin/netqueue-apply.sh apply-nic
}
